/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package warteg;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormPemesanan extends javax.swing.JFrame {

    /**
     * Creates new form FormPemesanan
     */
    public FormPemesanan() {
        initComponents();
        Data.inisialisasidata();
        tampildata();
        Total.setEnabled(false);
        Hapus.setVisible(false);
        Update.setVisible(false);
        Reset.setVisible(false);
        peringatanJumlah.setVisible(false);
        peringatanHarga.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        Tambah = new javax.swing.JButton();
        Kode = new javax.swing.JTextField();
        Makanan = new javax.swing.JTextField();
        Jumlah = new javax.swing.JTextField();
        Harga = new javax.swing.JTextField();
        Total = new javax.swing.JTextField();
        Update = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Cari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        peringatanJumlah = new javax.swing.JLabel();
        peringatanHarga = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Makanan", "Jumlah", "Harga", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        Tambah.setText("Tambah Menu");
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });

        Jumlah.setText("0");
        Jumlah.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JumlahFocusLost(evt);
            }
        });
        Jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JumlahKeyReleased(evt);
            }
        });

        Harga.setText("0");
        Harga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                HargaFocusLost(evt);
            }
        });
        Harga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                HargaKeyReleased(evt);
            }
        });

        Total.setText("0");

        Update.setText("Update Menu");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Hapus.setText("Hapus Menu");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });

        Reset.setText("Reset ");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        jLabel1.setText("Kode");

        jLabel2.setText("Makanan");

        jLabel3.setText("Jumlah");

        jLabel4.setText("Harga");

        jLabel5.setText("Total");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        peringatanJumlah.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        peringatanJumlah.setForeground(new java.awt.Color(255, 0, 0));
        peringatanJumlah.setText("Jumlah harus berbentuk bilangan");

        peringatanHarga.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        peringatanHarga.setForeground(new java.awt.Color(255, 0, 0));
        peringatanHarga.setText("Harga harus berbentuk bilangan");

        jLabel6.setFont(new java.awt.Font("Bodoni MT", 0, 24)); // NOI18N
        jLabel6.setText("Sistem Informasi Warteg");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Tambah)
                .addGap(18, 18, 18)
                .addComponent(Update)
                .addGap(18, 18, 18)
                .addComponent(Hapus)
                .addGap(18, 18, 18)
                .addComponent(Reset)
                .addGap(33, 112, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Makanan)
                            .addComponent(Jumlah)
                            .addComponent(Harga)
                            .addComponent(Total)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(peringatanHarga)
                                    .addComponent(peringatanJumlah))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(Kode)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Cari, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Makanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(peringatanJumlah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(peringatanHarga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tambah)
                    .addComponent(Update)
                    .addComponent(Hapus)
                    .addComponent(Reset))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
        // TODO add your handling code here:
        if (Kode.getText().isEmpty() || Makanan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Data Tidak Boleh Kosong !");
        } else if (CariByKode(Kode.getText()) == Menu.menu.size()) {
            try {
                Menu.menu.add(new Menu(Kode.getText(), Makanan.getText(), Integer.parseInt(Jumlah.getText()), Integer.parseInt(Harga.getText()), Integer.parseInt(Total.getText())));
                Data.writeFile();
                tampildata();
                JOptionPane.showMessageDialog(this, "Sukses Tambah Data !");
                Reset();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Jumlah dan Harga harus berbentuk bilangan !");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Data sudah ada", "Error", JOptionPane.CANCEL_OPTION);
        }

    }//GEN-LAST:event_TambahActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        Hapus.setVisible(true);
        Update.setVisible(true);
        Reset.setVisible(true);
        Kode.setEnabled(false);
        int index = tabel.getSelectedRow();
        Kode.setText(Menu.menu.get(index).getKode_makanan());
        Makanan.setText(Menu.menu.get(index).getNama_makanan());
        Harga.setText(Menu.menu.get(index).getHarga() + "");
        Jumlah.setText(Menu.menu.get(index).getJumlah() + "");
        Total.setText(Menu.menu.get(index).getTotal() + "");
    }//GEN-LAST:event_tabelMouseClicked

    private void JumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JumlahKeyReleased
        // TODO add your handling code here:
        peringatanJumlah.setVisible(false);
        try {
            Total.setText(Integer.parseInt(Jumlah.getText()) * Integer.parseInt(Harga.getText()) + "");
        } catch (NumberFormatException e) {
            if (Jumlah.getText().equals("")) {
                Total.setText(0 + "");
            } else {
                peringatanJumlah.setVisible(true);
            }
        }
    }//GEN-LAST:event_JumlahKeyReleased

    private void HargaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HargaKeyReleased
        // TODO add your handling code here:
        peringatanHarga.setVisible(false);
        try {
            Total.setText(Integer.parseInt(Jumlah.getText()) * Integer.parseInt(Harga.getText()) + "");
        } catch (NumberFormatException e) {
            if (Harga.getText().equals("")) {
                Total.setText(0 + "");
            } else {
                peringatanJumlah.setVisible(true);
            }
        }
    }//GEN-LAST:event_HargaKeyReleased

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        if (CariByKode(Kode.getText()) != Menu.menu.size()) {
            try {
                Menu.menu.set(CariByKode(Kode.getText()), new Menu(Kode.getText(), Makanan.getText(), Integer.parseInt(Jumlah.getText()), Integer.parseInt(Harga.getText()), Integer.parseInt(Total.getText())));
                Data.writeFile();
                tampildata();
                JOptionPane.showMessageDialog(this, "Sukses Ubah Data !", "Sukses", JOptionPane.DEFAULT_OPTION);
                Reset();
            } catch (Exception e) {
                System.out.println("Error : " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Data tidak ada", "Error", JOptionPane.CANCEL_OPTION);
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        int hapus = JOptionPane.showConfirmDialog(this, "Anda yakin Menghapus Data ?", "Hapus", JOptionPane.YES_NO_OPTION);
        if (hapus == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(this, "Data batal dihapus !");
        } else if (hapus == JOptionPane.CLOSED_OPTION) {

        } else if (CariByKode(Kode.getText()) != Menu.menu.size()) {
            try {
                Menu.menu.remove(CariByKode(Kode.getText()));
                if (Menu.menu.isEmpty()) {
                    DefaultTableModel a = (DefaultTableModel) tabel.getModel();
                    a.removeRow(0);
                }
                Data.writeFile();
                tampildata();
                JOptionPane.showMessageDialog(this, "Sukses Hapus Data !", "Sukses", JOptionPane.DEFAULT_OPTION);
                Reset();
            } catch (Exception e) {
                System.out.println("Error : " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Data tidak ada", "Error", JOptionPane.CANCEL_OPTION);
        }
    }//GEN-LAST:event_HapusActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        Reset();
    }//GEN-LAST:event_ResetActionPerformed

    private void HargaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_HargaFocusLost
        // TODO add your handling code here:
        if (Harga.getText().equals("")) {
            Harga.setText(0 + "");
        }
    }//GEN-LAST:event_HargaFocusLost

    private void JumlahFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JumlahFocusLost
        // TODO add your handling code here:
        if (Jumlah.getText().equals("")) {
            Jumlah.setText(0 + "");
        }
    }//GEN-LAST:event_JumlahFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int i = CariByKode(Cari.getText());
        if (i >= Menu.menu.size()) {
            JOptionPane.showMessageDialog(this, "Data kosong!");
            tampildata();
        } else {
            DefaultTableModel a = (DefaultTableModel) tabel.getModel();
            a.getDataVector().removeAllElements();
            Object[] baris = new Object[5];

            baris[0] = Menu.menu.get(i).getKode_makanan();
            baris[1] = Menu.menu.get(i).getNama_makanan();
            baris[2] = Menu.menu.get(i).getJumlah();
            baris[3] = Menu.menu.get(i).getHarga();
            baris[4] = Menu.menu.get(i).getTotal();
            a.addRow(baris);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void Reset() {
        Kode.setText("");
        Makanan.setText("");
        Harga.setText("0");
        Jumlah.setText("0");
        Total.setText("0");
        Kode.setEnabled(true);
        Update.setVisible(false);
        Hapus.setVisible(false);
        Reset.setVisible(false);
        Tambah.setVisible(true);
    }

    public int CariByKode(String Kode) {
        int i = 0;
        for (; i < Menu.menu.size(); i++) {
            if (Menu.menu.get(i).getKode_makanan().equals(Kode)) {
                break;
            }
        }
        return i;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPemesanan().setVisible(true);
            }
        });
    }

    public void tampildata() {
        DefaultTableModel a = (DefaultTableModel) tabel.getModel();
        a.getDataVector().removeAllElements();
        Object[] baris = new Object[5];
        for (int i = 0; i < Menu.menu.size(); i++) {
            baris[0] = Menu.menu.get(i).getKode_makanan();
            baris[1] = Menu.menu.get(i).getNama_makanan();
            baris[2] = Menu.menu.get(i).getJumlah();
            baris[3] = Menu.menu.get(i).getHarga();
            baris[4] = Menu.menu.get(i).getTotal();
            a.addRow(baris);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cari;
    private javax.swing.JButton Hapus;
    private javax.swing.JTextField Harga;
    private javax.swing.JTextField Jumlah;
    private javax.swing.JTextField Kode;
    private javax.swing.JTextField Makanan;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Tambah;
    private javax.swing.JTextField Total;
    private javax.swing.JButton Update;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel peringatanHarga;
    private javax.swing.JLabel peringatanJumlah;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
